name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  export-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Recreate debug keystore
        shell: bash
        run: |
          echo "${{ secrets.ANDROID_DEBUG_KEYSTORE_B64 }}" | base64 -d > debug.keystore
          ls -l debug.keystore

      - name: Export Godot project
        id: export
        uses: firebelley/godot-export@v7.0.0
        env:
          GODOT_ANDROID_KEYSTORE_DEBUG_PATH: ${{ github.workspace }}/debug.keystore
          GODOT_ANDROID_KEYSTORE_DEBUG_USER: ${{ secrets.ANDROID_DEBUG_KEYSTORE_USER }}
          GODOT_ANDROID_KEYSTORE_DEBUG_PASSWORD: ${{ secrets.ANDROID_DEBUG_KEYSTORE_PASSWORD }}
        with:
          godot_executable_download_url: https://godot-releases.nbg1.your-objectstorage.com/4.6.2-stable/Godot_v4.6.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://godot-releases.nbg1.your-objectstorage.com/4.6.2-stable/Godot_v4.6.2-stable_export_templates.tpz
          relative_project_path: ./
          export_debug: true
          presets_to_export: Android
          use_preset_export_path: true
          cache: true
          archive_output: false
          verbose: true

      - name: Show exported files
        run: find . -type f | grep -E '\.apk$|build/'

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/game.apk
          if-no-files-found: error
          retention-days: 14
